### ISSUE TITLE
Option to fail grunt task if audit fails

### ISSUE THREAD

**Issue by jrcryer** [lucalanca/grunt-a11y#2]
It would be good to hear your thoughts on whether the grunt task should fail if one or more of the audit's fails.

**Comment by lucalanca** [comment]
@jrcryer just released version `0.1.1` with this feature. You can see how to use it in the [README](https://github.com/lucalanca/grunt-a11y#optionsfailonerror). Can you please confirm it works for you?

**Comment by jrcryer** [comment]
Works great :+1: Thanks!
